AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
Developer.create(name: Faker::Color.color_name, url: Faker::Internet.url, description:Faker::Lorem.sentence, is_live: true, slug: 'A Developer URL Slug')
App.create(name: Faker::Name.name, description:Faker::Lorem.sentence, is_live:true, info_url:Faker::Internet.url, developer_id:1, slug: 'An App URL Slug')
Distributor.create(name: Faker::Dessert.variety, badge_image_url:Faker::Internet.url, is_live:true)
DistributorLink.create(link:Faker::Internet.url, app_store_id:1, app_id: 1, is_live: true)
Product.create(name: Faker::Fallout.character, description: Faker::Lorem.sentence, shop_link:Faker::Internet.url, is_live:true)
WorksWith.create(title:Faker::Lorem.sentence, description: Faker::Lorem.sentence, is_live: true, product_id:1, app_id: 1, promo_text:Faker::Lorem.sentence, promo_image_url:Faker::Internet.url, slug: 'A Works With URL Slug')
Testimonial.create(title: Faker::Lorem.sentence, description:Faker::Lorem.sentence, promo_text:Faker::Lorem.sentence, promo_image_url:Faker::Internet.url, is_live: true, works_with_id: 1, publish_date: Faker::Date.backward(2),slug: 'A Testimonial URL Slug')
UseCase.create(title:Faker::Lorem.sentence, description: Faker::Lorem.sentence, is_live: true, works_with_id: 1, slug: 'A Use Case URL Slug')
ExampleImage.create(image_url:Faker::Internet.url, caption: Faker::Lorem.sentence, works_with_id:1, is_live:true)
TestimonialSlide.create(image_url:Faker::Internet.url, caption: Faker::Lorem.sentence, testimonial_id:1, sequence_number: 1, is_live:true)